- name: Install ppa key
  apt_key:
      url: https://www.mongodb.org/static/pgp/server-3.2.asc
      state: present

- name: Update apt packages
  apt:
    update_cache: true
  tags: install

- name: App repo
  apt_repository:
    repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
    state: present
  tags: install

- name: Install DB
  apt:
    allow_unauthenticated: yes
    name: mongodb-org
    state: present
  tags: install

- name: Enable autostart DB
  systemd:
    name: mongod
    enabled: yes
  tags: install
